# This is a basic workflow to help you get started with Actions

name: Store update when PR is merged

# Controls when the workflow will run
on:
  # Run every day
  pull_request:
    types: [ closed ]

  workflow_dispatch:

jobs:
  update-store:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12' ]
    name: Update store
    steps:
      - uses: actions/checkout@v2
      - name: Run script to update store
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build
      - run: npm run update-store ${{ secrets.GH_API_KEY }}