# This is a basic workflow to help you get started with Actions

name: Store update

# Controls when the workflow will run
on:
  # Run every 12 hour
  schedule:
  - cron: "0 0 * * *"
  - cron: "0 12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-store:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12' ]
    name: Update store
    steps:
      - uses: actions/checkout@v2
      - name: Run script to update store
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build
      - run: npm run update-store ${{ secrets.GH_API_KEY }}
